apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-store
  template:
    metadata:
      labels:
        app: file-store
    spec:
      containers:
      - name: file-store
        image: prakhargupta05/file_store:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /app/server/storage
          name: file-store-data
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5
      volumes:
      - name: file-store-data
        persistentVolumeClaim:
          claimName: file-store-pvc
